name: "Build kernel."              # Description of the workflow.
on:
  push:
    branches: |
          4.9-addison
          4.9-addison-workflow
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: msm8953_defconfig                    # Specify defconfig to use
        image: Image.gz-dtb                           # Specify final build file
    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: ${{ github.repository }} on ${{ github.sha }} is built!
        document:  ${{ steps.build.outputs.outfile }}
    - name: Debugging
#      run: find / -name "Image.gz-dtb" 2>/dev/null
      run: find /home/runner/work/kernel-msm8953/kernel-msm8953/ -type f -name "*.zip" -exec ls -l {} \;
  #  - name: Setup upterm session
  #    uses: lhotari/action-upterm@v1
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /home/runner/work/kernel-msm8953/kernel-msm8953/out/arch/arm64/boot/Image.gz-dtb 
        
# credit to https://forum.xda-developers.com/t/dev-script-android-kernel-actions-easily-create-an-environment-and-build-android-kernels-with-github-action.4301481/
